// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWk0dYKLmV_I9_IQ6xcdmx9g-IeVsowic',
    appId: '1:784384238453:web:e67869449e5a81bb4ce93c',
    messagingSenderId: '784384238453',
    projectId: 'lingo-375714',
    authDomain: 'lingo-375714.firebaseapp.com',
    storageBucket: 'lingo-375714.appspot.com',
    measurementId: 'G-DCL9ETFJ5W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDefW8t-NQJ5Tj0tE5oR_nW3cyhglC6H2k',
    appId: '1:784384238453:android:3fd35c0db71568d44ce93c',
    messagingSenderId: '784384238453',
    projectId: 'lingo-375714',
    storageBucket: 'lingo-375714.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMpbJlfx-DheiF8KHBDbionr_wLDMU_rs',
    appId: '1:784384238453:ios:f2a1542321bc51554ce93c',
    messagingSenderId: '784384238453',
    projectId: 'lingo-375714',
    storageBucket: 'lingo-375714.appspot.com',
    iosClientId: '784384238453-s6og0p74o4qkmrpea23b5klaep4c8chg.apps.googleusercontent.com',
    iosBundleId: 'com.example.bebop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMpbJlfx-DheiF8KHBDbionr_wLDMU_rs',
    appId: '1:784384238453:ios:f2a1542321bc51554ce93c',
    messagingSenderId: '784384238453',
    projectId: 'lingo-375714',
    storageBucket: 'lingo-375714.appspot.com',
    iosClientId: '784384238453-s6og0p74o4qkmrpea23b5klaep4c8chg.apps.googleusercontent.com',
    iosBundleId: 'com.example.bebop',
  );
}
